#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

pushd $OPENSHIFT_REPO_DIR/resources

echo "Creating foodmart configuration datasource file."
cat foodmart | sed -e 's/\${env:OPENSHIFT_MYSQL_DB_HOST}/'${OPENSHIFT_MYSQL_DB_HOST}'/' -e 's/\${env:OPENSHIFT_MYSQL_DB_PORT}/'${OPENSHIFT_MYSQL_DB_PORT}'/' -e 's/\${env:OPENSHIFT_APP_NAME}/'${OPENSHIFT_APP_NAME}'/' -e 's/\${env:OPENSHIFT_MYSQL_DB_USERNAME}/'${OPENSHIFT_MYSQL_DB_USERNAME}'/' -e 's/\${env:OPENSHIFT_MYSQL_DB_PASSWORD}/'${OPENSHIFT_MYSQL_DB_PASSWORD}'/' > $OPENSHIFT_REPO_DIR/webapps/saiku/WEB-INF/classes/saiku-datasources/foodmart
echo "Foodmart configuration file created."
